//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.10 at 01:52:14 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.morgantest.com/main")
package com.morgantest.main;
